# Generated by Django 6.0 on 2025-12-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CanteenItems',
            fields=[
                ('item_name', models.TextField(primary_key=True, serialize=False)),
                ('price_rs', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('protein_g', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('calories_kcal', models.IntegerField(blank=True, null=True)),
                ('rating_out_of_5', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
            ],
            options={
                'db_table': 'canteen_items',

            },
        ),
    ]
